src/br/com/sam/bean/ConsultaAgendamentoBean.java
package br.com.sam.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpSession;
import javax.swing.JOptionPane;

import br.com.sam.web.dao.AgendamentoOnlineDAO;
import br.com.sam.web.mb.AgendamentoOnline;

@Named
@SessionScoped
public class ConsultaAgendamentoBean implements Serializable{

	@EJB
	private AgendamentoOnlineDAO agendamentoOnlineDAO;
	
	@Inject
	private Autenticador autenticador;
	
	private Integer opcaoMenuData = new Integer(0);
	
	private Long idClinica;
	
	private List<AgendamentoOnline> listAgendamentoOnline;
	
	private Date deAgendamento;
	
	private Date ateAgendamento;
	
	private String ultimoAno;
	private String primeiroAno;
	
	private String nomeMedico = "";
	
	@PostConstruct
	public void init()
	{
		try
		{
			idClinica = autenticador.getClinica().getId();
			ultimoAno = String.valueOf(agendamentoOnlineDAO.getAgendamentoOnlineUltimoAno(idClinica));
			primeiroAno = String.valueOf(agendamentoOnlineDAO.getAgendamentoOnlinePrimeiroAno(idClinica));
		}
		catch (Exception e) {
			// TODO: handle exception
		}
		
	}
	
	public void atualizarAgendamentos()
	{
		if(nomeMedico == null)
		{
			nomeMedico = "";
		}
		System.out.println(opcaoMenuData + "--");
		if(opcaoMenuData == 1)
		{
			System.out.println("Hoje");
			listAgendamentoOnline = null;
			listAgendamentoOnline = agendamentoOnlineDAO.getAgendamentosAdminHoje(idClinica, nomeMedico);
			
		}
		else if(opcaoMenuData == 2)
		{
			System.out.println("AgendamentoFuturo");
			listAgendamentoOnline = null;
			listAgendamentoOnline = agendamentoOnlineDAO.getAgendamentosAdminFuturos(idClinica, nomeMedico);
		}
		
		else if(opcaoMenuData == 3)
		{
			getListAgendamentoOnlinePeriodo();
		}
	}
	
	public void getListAgendamentoOnlinePeriodo()
	{
		System.out.println("Periodo");
		if(ateAgendamento != null)
		{
			System.out.println("Escolher Periodo");
			listAgendamentoOnline = agendamentoOnlineDAO.getAgendamentosPeriodo(idClinica, deAgendamento, ateAgendamento, nomeMedico);
		}
	}
	
	public List<String> getMedicos()
	{
		return agendamentoOnlineDAO.getMedicos();
	}
		
	public String encerrarSessao()
	{
		String id = idClinica.toString();
		((HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false)).invalidate();
		
		return "/agendamento-online/login.xhtml?param=" + id + "&faces-redirect=true";
	}
	
	public void limpar()
	{
		opcaoMenuData = 0;
		listAgendamentoOnline = null;
		deAgendamento = null;
		ateAgendamento = null;
		ultimoAno = "";
		primeiroAno = "";
		nomeMedico = "";
	}
	public List<AgendamentoOnline> getListAgendamentoOnline() {
		return listAgendamentoOnline;
	}
	public void setListAgendamentoOnline(List<AgendamentoOnline> listAgendamentoOnline) {
		this.listAgendamentoOnline = listAgendamentoOnline;
	}

	public Integer getOpcaoMenuData() {
		return opcaoMenuData;
	}

	public void setOpcaoMenuData(Integer opcaoMenuData) {
		this.opcaoMenuData = opcaoMenuData;
	}

	public Date getDeAgendamento() {
		return deAgendamento;
	}

	public void setDeAgendamento(Date deAgendamento) {
		this.deAgendamento = deAgendamento;
	}

	public Date getAteAgendamento() {
		return ateAgendamento;
	}

	public void setAteAgendamento(Date ateAgendamento) {
		this.ateAgendamento = ateAgendamento;
	}

	public String getUltimoAno() {
		return ultimoAno;
	}

	public void setUltimoAno(String ultimoAno) {
		this.ultimoAno = ultimoAno;
	}

	public String getPrimeiroAno() {
		return primeiroAno;
	}

	public void setPrimeiroAno(String primeiroAno) {
		this.primeiroAno = primeiroAno;
	}

	public String getNomeMedico() {
		return nomeMedico;
	}

	public void setNomeMedico(String nomeMedico) {
		this.nomeMedico = nomeMedico;
	}
}

apache-tomcat-10.0.13/webapps/examples/WEB-INF/classes/async/AsyncStockServlet.java
/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package async;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.atomic.AtomicInteger;

import jakarta.servlet.AsyncContext;
import jakarta.servlet.AsyncEvent;
import jakarta.servlet.AsyncListener;
import jakarta.servlet.ServletContext;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import org.apache.juli.logging.Log;
import org.apache.juli.logging.LogFactory;

import async.Stockticker.Stock;
import async.Stockticker.TickListener;

public class AsyncStockServlet extends HttpServlet implements TickListener, AsyncListener{

    private static final long serialVersionUID = 1L;

    private static final Log log = LogFactory.getLog(AsyncStockServlet.class);

    private static final ConcurrentLinkedQueue<AsyncContext> clients =
            new ConcurrentLinkedQueue<>();
    private static final AtomicInteger clientcount = new AtomicInteger(0);

    public AsyncStockServlet() {
        log.info("AsyncStockServlet created");
    }


    @Override
    protected void service(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {
        if (req.isAsyncStarted()) {
            req.getAsyncContext().complete();
        } else if (req.isAsyncSupported()) {
            AsyncContext actx = req.startAsync();
            actx.addListener(this);
            resp.setContentType("text/plain");
            clients.add(actx);
            if (clientcount.incrementAndGet()==1) {
                Stockticker ticker = (Stockticker) req.getServletContext().getAttribute(
                        AsyncStockContextListener.STOCK_TICKER_KEY);
                ticker.addTickListener(this);
            }
        } else {
            new Exception("Async Not Supported").printStackTrace();
            resp.sendError(400,"Async is not supported.");
        }
    }


    @Override
    public void tick(Stock stock) {
        for (AsyncContext actx : clients) {
            try {
                writeStock(actx, stock);
            } catch (Exception e) {
                // Ignore. The async error handling will deal with this.
            }
        }
    }


    public void writeStock(AsyncContext actx, Stock stock) throws IOException {
        HttpServletResponse response = (HttpServletResponse)actx.getResponse();
        PrintWriter writer = response.getWriter();
        writer.write("STOCK#");//make client parsing easier
        writer.write(stock.getSymbol());
        writer.write("#");
        writer.write(stock.getValueAsString());
        writer.write("#");
        writer.write(stock.getLastChangeAsString());
        writer.write("#");
        writer.write(String.valueOf(stock.getCnt()));
        writer.write("\n");
        writer.flush();
        response.flushBuffer();
    }


    @Override
    public void shutdown() {
        // The web application is shutting down. Complete any AsyncContexts
        // associated with an active client.
        for (AsyncContext actx : clients) {
            try {
                actx.complete();
            } catch (Exception e) {
                // Ignore. The async error handling will deal with this.
            }
        }
    }


    @Override
    public void onComplete(AsyncEvent event) throws IOException {
        if (clients.remove(event.getAsyncContext()) && clientcount.decrementAndGet()==0) {
            ServletContext sc = event.getAsyncContext().getRequest().getServletContext();
            Stockticker ticker = (Stockticker) sc.getAttribute(
                    AsyncStockContextListener.STOCK_TICKER_KEY);
            ticker.removeTickListener(this);
        }
    }

    @Override
    public void onError(AsyncEvent event) throws IOException {
        event.getAsyncContext().complete();
    }

    @Override
    public void onTimeout(AsyncEvent event) throws IOException {
        event.getAsyncContext().complete();
    }


    @Override
    public void onStartAsync(AsyncEvent event) throws IOException {
        // NOOP
    }
}

apache-tomcat-10.0.13/webapps/examples/WEB-INF/classes/cal/TableBean.java
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package cal;

import java.util.Hashtable;

import jakarta.servlet.http.HttpServletRequest;

public class TableBean {

    final Hashtable<String, Entries> table;
    final JspCalendar JspCal;
    Entries entries;
    String date;
    String name = null;
    String email = null;
    boolean processError = false;

    public TableBean() {
        this.table = new Hashtable<>(10);
        this.JspCal = new JspCalendar();
        this.date = JspCal.getCurrentDate();
    }

    public void setName(String nm) {
        this.name = nm;
    }

    public String getName() {
        return this.name;
    }

    public void setEmail(String mail) {
        this.email = mail;
    }

    public String getEmail() {
        return this.email;
    }

    public String getDate() {
        return this.date;
    }

    public Entries getEntries() {
        return this.entries;
    }

    public void processRequest(HttpServletRequest request) {

        // Get the name and e-mail.
        this.processError = false;
        if (name == null || name.equals("")) {
            setName(request.getParameter("name"));
        }
        if (email == null || email.equals("")) {
            setEmail(request.getParameter("email"));
        }
        if (name == null || email == null || name.equals("")
                || email.equals("")) {
            this.processError = true;
            return;
        }

        // Get the date.
        String dateR = request.getParameter("date");
        if (dateR == null) {
            date = JspCal.getCurrentDate();
        } else if (dateR.equalsIgnoreCase("next")) {
            date = JspCal.getNextDate();
        } else if (dateR.equalsIgnoreCase("prev")) {
            date = JspCal.getPrevDate();
        }

        entries = table.get(date);
        if (entries == null) {
            entries = new Entries();
            table.put(date, entries);
        }

        // If time is provided add the event.
        String time = request.getParameter("time");
        if (time != null) {
            entries.processRequest(request, time);
        }
    }

    public boolean getProcessError() {
        return this.processError;
    }
}

apache-tomcat-10.0.13/webapps/examples/WEB-INF/classes/colors/ColorGameBean.java
/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
package colors;

public class ColorGameBean {

    private String background = "yellow";
    private String foreground = "red";
    private String color1 = foreground;
    private String color2 = background;
    private String hint = "no";
    private int attempts = 0;
        private int intval = 0;
    private boolean tookHints = false;

    public void processRequest() {

        // background = "yellow";
        // foreground = "red";

        if (! color1.equals(foreground)) {
            if (color1.equalsIgnoreCase("black") ||
                        color1.equalsIgnoreCase("cyan")) {
                        background = color1;
                }
        }

        if (! color2.equals(background)) {
            if (color2.equalsIgnoreCase("black") ||
                        color2.equalsIgnoreCase("cyan")) {
                        foreground = color2;
            }
        }

        attempts++;
    }

    public void setColor2(String x) {
        color2 = x;
    }

    public void setColor1(String x) {
        color1 = x;
    }

    public void setAction(String x) {
        if (!tookHints) {
            tookHints = x.equalsIgnoreCase("Hint");
        }
        hint = x;
    }

    public String getColor2() {
         return background;
    }

    public String getColor1() {
         return foreground;
    }

    public int getAttempts() {
        return attempts;
    }

    public boolean getHint() {
        return hint.equalsIgnoreCase("Hint");
    }

    public boolean getSuccess() {
        if (background.equalsIgnoreCase("black") ||
            background.equalsIgnoreCase("cyan")) {

            if (foreground.equalsIgnoreCase("black") ||
                foreground.equalsIgnoreCase("cyan")) {
                return true;
            }
            return false;
        }

        return false;
    }

    public boolean getHintTaken() {
        return tookHints;
    }

    public void reset() {
        foreground = "red";
        background = "yellow";
    }

    public void setIntval(int value) {
        intval = value;
        }

    public int getIntval() {
        return intval;
        }
}

apache-tomcat-10.0.13/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilterTestServlet.java
/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
package compressionFilters;

import java.io.IOException;
import java.util.Enumeration;

import jakarta.servlet.ServletException;
import jakarta.servlet.ServletOutputStream;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Very Simple test servlet to test compression filter
 * @author Amy Roh
 */
public class CompressionFilterTestServlet extends HttpServlet {

    private static final long serialVersionUID = 1L;

    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {

        ServletOutputStream out = response.getOutputStream();
        response.setContentType("text/plain");

        Enumeration<String> e = request.getHeaders("Accept-Encoding");
        while (e.hasMoreElements()) {
            String name = e.nextElement();
            out.println(name);
            if (name.indexOf("gzip") != -1) {
                out.println("gzip supported -- able to compress");
            } else {
                out.println("gzip not supported");
            }
        }


        out.println("Compression Filter Test Servlet");
        out.println("Minimum content length for compression is 128 bytes");
        out.println("**********  32 bytes  **********");
        out.println("**********  32 bytes  **********");
        out.println("**********  32 bytes  **********");
        out.println("**********  32 bytes  **********");
        out.close();
    }

}

WebContent/WEB-INF/admin/alterar-senha.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:p="http://primefaces.org/ui">
		
	<h:form>
		<h1 style="text-align: center">Alteração de Senha</h1>
		
		<div class="ui-fluid">
			<p:messages closable="true">
				<p:autoUpdate></p:autoUpdate>
			</p:messages>
			
			<p:panelGrid layout="grid" columns="2" columnClasses="ui-grid-col-2, ui-grid-col-4" styleClass="panelgrid-noborder" style="margin-top: 10px; padding-top:20px; border-top: 1px solid #ddd">
				<p:outputLabel for="senhaAtual" value="Senha atual: "></p:outputLabel>
				<p:password id="senhaAtual" value="#{alterarCadastroAdminBean.senhaAtual}" required="true"></p:password>
			</p:panelGrid>
		
			<p:panelGrid layout="grid" columns="4" columnClasses="ui-grid-col-2, ui-grid-col-4, ui-grid-col-2, ui-grid-col-4" styleClass="panelgrid-noborder" style="margin-top: 10px; padding-top:20px; border-top: 1px solid #ddd">
				<p:outputLabel for="confirmarSenha" value="Nova Senha:"></p:outputLabel>
	            <p:password id="confirmarSenha" match="confirmarNovaSenha" value="#{alterarCadastroAdminBean.novaSenha}"  required="true" placeholder="Nova senha (Mínimo 6 caracteres)" feedback="true" inline="true" weakLabel="Fraca" strongLabel="Forte" goodLabel="Boa" promptLabel="Insira a sua senha">
	            	<f:validateLength minimum="6"></f:validateLength>
	            </p:password>
				
				<p:outputLabel for="confirmarNovaSenha" value="Confirmar Senha:"></p:outputLabel>
	           	<p:password id="confirmarNovaSenha" value="#{alterarCadastroAdminBean.novaSenha}" required="true" placeholder="Confirmar a nova senha" ></p:password>
			</p:panelGrid>
			
			<p:panelGrid columns="1" layout="grid" columnClasses="ui-grid-col-12" styleClass="panelgrid-noborder">
				<h:panelGroup style="text-align: right;" layout="block">
					<h:outputText value="Campos OBRIGATÓRIOS(*)" style="font-size: small"/>
				</h:panelGroup>
				
				<p:commandButton id="btnEnter" value="Alterar Senha" action="#{alterarCadastroAdminBean.merge()}" process="@form" update="@form" icon="fa fa-check" styleClass="icon-maior"></p:commandButton>
			</p:panelGrid>
			
			<p:defaultCommand target="btnEnter"></p:defaultCommand>
			
		</div>
		
	</h:form>
</html>

WebContent/WEB-INF/admin/consulta-agendamentos.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:p="http://primefaces.org/ui">
		
	<h:form>
		<p:panel header="Consulta de Agendamentos" style="margin-bottom: 20px;">
			<div class="ui-fluid">
				<p:panelGrid id="panelgrid-selecao" columns="4" layout="grid" columnClasses="ui-grid-col-2, ui-grid-col-4, ui-grid-col-2, ui-grid-col-4" styleClass="panelgrid-noborder" >
					<p:outputLabel for="medicoConsultaOneMenu" value="Médico: &#160;" escape="false"></p:outputLabel>
					<p:selectOneMenu id="medicoConsultaOneMenu" value="#{consultaAgendamentoBean.nomeMedico}">
						<f:selectItem itemLabel="TODOS" itemValue=""/>
						<f:selectItems value="#{consultaAgendamentoBean.medicos}" var="m" itemLabel="#{m}" itemValue="#{m}" />
						<p:ajax event="itemSelect" process="@this" update="panelAgendamentos" listener="#{consultaAgendamentoBean.atualizarAgendamentos()}"></p:ajax>
					</p:selectOneMenu>
				
					<p:outputLabel for="dataConsultaOneMenu" value="Data:"></p:outputLabel>
					<p:selectOneMenu id="dataConsultaOneMenu" value="#{consultaAgendamentoBean.opcaoMenuData}">
						<f:selectItem itemLabel="Selecione..." noSelectionOption="true" />
						<f:selectItem itemLabel="Hoje" itemValue="1" />
						<f:selectItem itemLabel="Agendamentos Futuros" itemValue="2"/>
						<f:selectItem itemLabel="Escolher Período" itemValue="3"/>
						
						<p:ajax event="itemSelect" process="@this medicoConsultaOneMenu" update="panelAgendamentos panelgrid-selecao" listener="#{consultaAgendamentoBean.atualizarAgendamentos()}"></p:ajax>
					</p:selectOneMenu>
					
					<p:outputLabel for="deAgendamento" value="De: " rendered="#{consultaAgendamentoBean.opcaoMenuData eq 3}"/>
					<p:calendar id="deAgendamento" value="#{consultaAgendamentoBean.deAgendamento}" navigator="true" yearRange="2018: #{consultaAgendamentoBean.ultimoAno}" rendered="#{consultaAgendamentoBean.opcaoMenuData eq 3}">
						<p:ajax event="dateSelect" process="@this" update="ateAgendamento panelAgendamentos" listener="#{consultaAgendamentoBean.getListAgendamentoOnlinePeriodo()}"></p:ajax>
					</p:calendar>
					
					<p:outputLabel for="ateAgendamento" value="Até: " rendered="#{consultaAgendamentoBean.opcaoMenuData eq 3}"/>
					<p:calendar id="ateAgendamento" value="#{consultaAgendamentoBean.ateAgendamento}" disabled="#{empty consultaAgendamentoBean.deAgendamento}" mindate="#{consultaAgendamentoBean.deAgendamento}" navigator="true" yearRange="2018: #{consultaAgendamentoBean.ultimoAno}" rendered="#{consultaAgendamentoBean.opcaoMenuData eq 3}">
						<p:ajax event="dateSelect" process="@this" listener="#{consultaAgendamentoBean.getListAgendamentoOnlinePeriodo()}" update="panelAgendamentos" ></p:ajax>
					</p:calendar>
				</p:panelGrid>
			</div>
			
			<p:outputPanel id="panelAgendamentos" style="padding-top: 10px;">
				<p:outputPanel rendered="#{consultaAgendamentoBean.opcaoMenuData eq 1}">
					<p:dataTable value="#{consultaAgendamentoBean.listAgendamentoOnline}" var="ao" scrollable="true" reflow="true" emptyMessage="Não há agendamentos para hoje" styleClass="datatable-meus-agendamentos">
						<f:facet name="header">
							<h:outputText value="Agendamentos" />
						</f:facet>
						<p:column headerText="Horario" width="10%">
							<h:outputText value="#{ao.hora}" />
						</p:column>
						
						<p:column headerText="Paciente">
							<h:outputText value="#{ao.beneficiario.nome}" />
						</p:column>
						
						<p:column headerText="Médico">
							<h:outputText value="#{ao.nmAgenda}" />
						</p:column>
						<f:facet name="footer">
							<h:outputText value="Há um total de #{consultaAgendamentoBean.listAgendamentoOnline.size()} agendamentos"  rendered="#{consultaAgendamentoBean.listAgendamentoOnline.size() gt 0}"/>
						</f:facet>
					</p:dataTable>
				</p:outputPanel>
				
				<p:outputPanel rendered="#{consultaAgendamentoBean.opcaoMenuData eq 2}">
					<p:dataTable value="#{consultaAgendamentoBean.listAgendamentoOnline}" var="ao" scrollable="true" reflow="true" emptyMessage="Não há agendamentos futuros" styleClass="datatable-meus-agendamentos">
						<f:facet name="header">
							<i class="fa fa-calendar"></i>
							<h:outputText value="Agendamentos" />
						</f:facet>
						
						<p:column headerText="Data">
							<h:outputText value="#{ao.dtAgenda.time}">
								<f:convertDateTime type="date" pattern="dd/MM/yyyy - EEEEEE" locale="pt"/>
							</h:outputText>
						</p:column>
						<p:column headerText="Horario" width="10%">
							<h:outputText value="#{ao.hora}" />
						</p:column>
						
						<p:column headerText="Paciente">
							<h:outputText value="#{ao.beneficiario.nome}" />
						</p:column>
						
						<p:column headerText="Médico">
							<h:outputText value="#{ao.nmAgenda}" />
						</p:column>
						
						<f:facet name="footer">
							<h:outputText value="Há um total de #{consultaAgendamentoBean.listAgendamentoOnline.size()} agendamentos" rendered="#{consultaAgendamentoBean.listAgendamentoOnline.size() gt 0}"/>
						</f:facet>
					</p:dataTable>
				</p:outputPanel>
				
				<p:outputPanel rendered="#{consultaAgendamentoBean.opcaoMenuData eq 3}">
					<p:dataTable id="datatableAgendamentos"  value="#{consultaAgendamentoBean.listAgendamentoOnline}" var="ao" scrollable="true" reflow="true" rendered="#{not empty consultaAgendamentoBean.ateAgendamento}" emptyMessage="Não há agendamentos para o período informado" styleClass="datatable-meus-agendamentos">
						<f:facet name="header">
							<h:outputText value="Agendamentos" />
						</f:facet>
						
						<p:column headerText="Data">
							<h:outputText value="#{ao.dtAgenda.time}">
								<f:convertDateTime type="date" pattern="dd/MM/yyyy - EEEEEE" locale="pt"/>
							</h:outputText>
						</p:column>
						
						<p:column headerText="Horario" width="10%">
							<h:outputText value="#{ao.hora}" />
						</p:column>
						
						<p:column headerText="Paciente">
							<h:outputText value="#{ao.beneficiario.nome}" />
						</p:column>
						
						<p:column headerText="Médico">
							<h:outputText value="#{ao.nmAgenda}" />
						</p:column>
						<f:facet name="footer">
							<h:outputText value="Há um total de #{consultaAgendamentoBean.listAgendamentoOnline.size()} agendamentos" rendered="#{consultaAgendamentoBean.listAgendamentoOnline.size() gt 0}"/>
						</f:facet>
					</p:dataTable>
				</p:outputPanel>
			</p:outputPanel>
		</p:panel>
	</h:form>
	
</html>